In [1]:
from owmeta_core.command import OWM
conn = OWM().connect()

from owmeta_core.context import Context
ctx = conn(Context)(ident='http://openworm.org/data')

from owmeta.worm import Worm
net = ctx.stored(Worm).query().neuron_network()

In [2]:
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import pandas as pd
import seaborn as sns

In [3]:
import os
import re

In [4]:
def sort_key(s):
    return [int(i) if i.isdigit() else i for i in re.split(r'(\d+)', s)]

In [5]:
neurons = list(net.neurons())
neurons.sort()

In [ ]:
# Iterate over each neuron to retrieve its channel(s)
channels = {}
for neuron in neurons:
    new_channels = list([channel for channel in neuron.channel()])
    for channel in new_channels:
        if channel.name() not in channels:
            channels[channel.name()] = channel

['EGL-36', 'KVS-1', 'OCR-2', 'MGL-3', 'OSM-9', 'KQT-3', 'TAX-4', 'CNG-3', 'EGL-2', 'TAX-2', 'MGL-1', 'GLR-2', 'GGR-1', 'GLR-1', 'LGC-46', 'GLC-3', 'CLH-1', 'UNC-8', 'UNC-36', 'MEC-10', 'LGC-55', 'KQT-1', 'AVR-15', 'TAG-180', 'FLR-1', 'CED-11', 'CLH-3', 'CCA-1', 'DEL-1', 'MOD-1', 'SHK-1', 'n/a', 'SLO-1', 'SLO-2', 'DEL-4', 'TRP-2', 'DEG-1', 'TRP-1', 'NMR-1', 'SUP-9', 'ACC-4', 'CLH-4', 'GTL-1', 'EXP-2', 'GLC-4', 'LGC-34', 'EGL-19', 'SHL-1', 'AVR-14', 'KCNL-2', 'GON-2', 'TWK-20', 'KQT-2', 'CLH-2', 'SHW-3']

In [15]:
exp2 = channels['EXP-2']
print(exp2.description())

exp-2 encodes a member of the six-transmembrane voltage-activated (Kv-type) family of potassium channels; exp-2 is required for normal pharyngeal muscle action potentials and hence, for normal feeding behavior; in addition, exp-2 is required for chemotaxis; when expressed in Xenopus oocytes, EXP-2 displays inward rectifying currents, however when assessed in endogenous pharyngeal tissue, EXP-2 displays hyperpolarization-activated outward currents; an EXP-2 translational reporter fusion is expressed strongly in pharyngeal muscles, amphid, phasmid, and head neurons, posterior enteric muscles, and occasionally faintly in the egg-laying muscles.

In [ ]:
neuron_to_receptors_dict = {'neuron':[], 'receptor':[]}
neurons = list(net.neurons())
neurons.sort()
receptors = dict()
for neuron in neurons:
    new_receptors = list(neuron.receptors())
    new_receptors.sort(key=sort_key)
    for receptor in new_receptors:
        neuron_to_receptors_dict['neuron'].append(neuron.name())
        neuron_to_receptors_dict['receptor'].append(receptor)
neuron_to_receptors_df = pd.DataFrame.from_dict(neuron_to_receptors_dict)
neuron_to_receptors_df.to_csv(os.path.join("data", "neuron_to_receptors.csv"), index=False)
neuron_to_receptors_df

     neuron receptor
0      ADEL   ACR-16
1      ADEL    DOP-2
2      ADEL    EXP-1
3      ADEL   OCTR-1
4      ADEL    TRP-4
...     ...      ...
1391    VD8    SER-2
1392    VD9    DOP-3
1393    VD9    MOD-1
1394    VD9    NPR-1
1395    VD9    SER-2

[1396 rows x 2 columns]

In [37]:
receptors = set()
for neuron in neurons:
    receptors = receptors | set(neuron.receptors())
receptors = list(receptors)
receptors.sort(key=sort_key)

with open(os.path.join('data', 'receptors.txt'), 'w') as f:
    for receptor in receptors:
        f.write(f"{receptor}\n")

In [ ]:
# Iterate over each neuron to retrieve its neurotransmitter(s)
neuron_to_nts_dict = {'neuron':[], 'neurotransmitter':[]}
for neuron in neurons:
    new_neurotransmitters = list(neuron.neurotransmitter())
    new_neurotransmitters.sort()
    for neurotransmitter in new_neurotransmitters:
        neuron_to_nts_dict['neuron'].append(neuron.name())
        neuron_to_nts_dict['neurotransmitter'].append(neurotransmitter)
neuron_to_nts_df = pd.DataFrame.from_dict(neuron_to_nts_dict)
neuron_to_nts_df.to_csv(os.path.join("data", "neuron_to_neurotransmitters.csv"), index=False)
neuron_to_nts_df

    neuron neurotransmitter
0     ADAL        Glutamate
1     ADAR        Glutamate
2     ADEL         Dopamine
3     ADER         Dopamine
4     ADFL        Serotonin
..     ...              ...
251    VD5             GABA
252    VD6             GABA
253    VD7             GABA
254    VD8             GABA
255    VD9             GABA

[256 rows x 2 columns]

In [38]:
nts = set()
for neuron in neurons:
    nts = nts | set(neuron.neurotransmitter())
nts = list(nts)
nts.sort()

with open(os.path.join('data', 'neurotransmitters.txt'), 'w') as f:
    for nt in nts:
        f.write(f"{nt}\n")

In [31]:
# Iterate over each neuron to retrieve its neuropeptide(s)
neuron_to_peptides_dict = {'neuron':[], 'neuropeptide':[]}
for neuron in neurons:
    new_neuropeptides = list(neuron.neuropeptide())
    new_neuropeptides.sort(key=sort_key)
    for neuropeptide in new_neuropeptides:
        neuron_to_peptides_dict['neuron'].append(neuron.name())
        neuron_to_peptides_dict['neuropeptide'].append(neuropeptide)
neuron_to_peptides_df = pd.DataFrame.from_dict(neuron_to_peptides_dict)
neuron_to_peptides_df.to_csv(os.path.join("data", "neuron_to_neuropeptides.csv"), index=False)        
neuron_to_peptides_df

    neuron neuropeptide
0     ADAL        FLP-8
1     ADAL        PDF-1
2     ADAR        FLP-8
3     ADAR        PDF-1
4     ADEL        PDF-1
..     ...          ...
516    VD7        NTC-1
517    VD8       FLP-11
518    VD8        NTC-1
519    VD9       FLP-11
520    VD9        NTC-1

[521 rows x 2 columns]

In [39]:
nps = set()
for neuron in neurons:
    nps = nps | set(neuron.neuropeptide())
nps = list(nps)
nps.sort(key=sort_key)

with open(os.path.join('data', 'neuropeptides.txt'), 'w') as f:
    for np in nps:
        f.write(f"{np}\n")

In [ ]:
channels = set()
for neuron in neurons:
    channels = channels | set([channel.name() for channel in neuron.channel()])
nps = list(nps)
nps.sort(key=sort_key)

with open(os.path.join('data', 'neuropeptides.txt'), 'w') as f:
    for np in nps:
        f.write(f"{np}\n")